apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $.Chart.Name }}-env"
data:
  JCARD_DB_HOST: "{{ default .Values.database.host }}"
  JCARD_DB_PORT: "{{ default .Values.database.port | quote }}"
  JCARD_DB_NAME: "{{ default .Values.database.name }}"