dev:
  configmap:
    data:
      variable1: valor1
      variable2: valor2
      variable3: valor3
sandbox:
  configmap:
    data:
      variable1: 1
      variable2: 2
      variable3: 3
qa:
  configmap:
    data:
      variable1: 1
      variable2: 2
      variable3: 3
prod:
  configmap:
    data:
      variable1: 1
      variable2: 2
      variable3: 3