dev:
  nombre: minuTosSSDFRE
  port: 8899
  database: bimo_jcard_dev
  service_account: bimo-jcard
sandbox:
  configmap:
    data:
      variable1: 1
      variable2: 2
      variable3: 3
qa:
  configmap:
    data:
      variable1: 1
      variable2: 2
      variable3: 3
