dev:
  nombre: minuTosSSDFRE
  port: 8899
  database: minuTosSSDFRE_Deve
sandbox:
  configmap:
    data:
      variable1: 1
      variable2: 2
      variable3: 3
qa:
  configmap:
    data:
      variable1: 1
      variable2: 2
      variable3: 3
