dev:
  nombre: prueba-issuer-3
  port: 29103
  database: prueba_issuer_dev_3
  service_account: xperience-jcard
  create_db: False
  external-sor: False

qa:
  nombre: prueba-issuer
  port: 29103
  database: prueba_issuer_qa
  service_account: xperience-jcard
  create_db: True
  external-sor: True



