dev:
  configmap:
    data:
      emisor: BIMO
      variable2: 22
sandbox:
  configmap:
    data:
      variable1: 1
      variable2: 2
      variable3: 3
qa:
  configmap:
    data:
      variable1: 1
      variable2: 2
      variable3: 3
prod:
  configmap:
    data:
      variable1: 1
      variable2: 2
      variable3: 3