apiVersion: v1
data:
  JOPTIONS: '{{ default .Values.java.joptions }}'
  LOG_ENCODER_TYPE: '{{ default .Values.java.logtype }}'
  PEDRO: '{{ default .Values.configmap.data.pedro}}'
  VARIABLE1: '{{ default .Values.configmap.data.variable1}}'
  VARIABLE2: '{{ default .Values.configmap.data.variable2}}'
  VARIABLE4: '{{ default .Values.configmap.data.variable4}}'
  VARIABLES: '{{ default .Values.configmap.data.variables}}'
kind: ConfigMap
metadata:
  name: '{{ $.Chart.Name }}-env'
