apiVersion: v1
kind: Service
metadata:
    name: {{ .Chart.Name }}-svc
    labels:
      run: backend
      type: {{ .Values.service.type }}
spec:
    ports:
    -   port: {{ .Values.service.port }}
        protocol: {{ .Values.service.protocol }}
        targetPort: {{ .Values.service.target_port }}
        name: {{ .Values.service.name }}
        nodePort: {{ .Values.service.node_port }}
    selector:
        app: {{ .Chart.Name }}
    type: NodePort
